# Generated by Django 4.2.7 on 2023-11-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["deadline"]},
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(default="In progress", max_length=255),
        ),
    ]
